# Site settings
title: Sudo MakeDev
description: 'Musings of the code making the dev.'
url: 'http://sudomakedev.com/'
baseurl: '/'
google_analytics: ' UA-91053139-1'
disqus_shortname: 'sudomakedev-com'

author:
  name: 'David Begg'
  email: drbegg@gmail.com
  twitter_username: TRG_Tafts
  #facebook_username: 
  github_username:  dbegg35
  #linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
